name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync-to-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Hugging Face Hub
        run: pip install huggingface_hub

      - name: Push Backend to automl-engine Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "import os; from huggingface_hub import HfApi; HfApi().upload_folder(folder_path='./backend', repo_id='fedede/automl-engine', repo_type='space', token=os.environ['HF_TOKEN'])"

      - name: Push Frontend to Streamlit Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "import os; from huggingface_hub import HfApi; HfApi().upload_folder(folder_path='./frontend', repo_id='fedede/automl-frontend', repo_type='space', token=os.environ['HF_TOKEN'])"