name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Crucial: Git needs the full history to perform a subtree split
          
      - name: Push to HF Spaces via Git Subtree
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add hf-backend https://fedede:$HF_TOKEN@huggingface.co/spaces/fedede/automl-engine
          git remote add hf-frontend https://fedede:$HF_TOKEN@huggingface.co/spaces/fedede/automl-frontend



          # 2. Isolate the backend folder and force push it to the backend space
          git subtree split --prefix backend -b deploy-backend
          git push hf-backend deploy-backend:main --force

          # 3. Isolate the frontend folder and force push it to the frontend space
          git subtree split --prefix frontend -b deploy-frontend
          git push hf-frontend deploy-frontend:main --force